export { default as CreatePin } from '../components/createPin/index';
export { default as Feed } from '../components/feed/index';
export { default as Login } from '../components/login/index';
export { default as Navbar } from '../components/navBar/index';
export { default as Sidebar } from '../components/sidebar/index';
export { default as UserProfile } from '../components/userProfile/index';
export { default as Search } from '../components/search/index';
export { default as PinDetail } from '../components/pinDetail/index';
export { default as Spinner } from '../components/spinner';
export { default as Pin } from '../components/pin';
export { default as MasonryLayout } from '../components/masonryLayout'
export { default as Galeria } from '../components/galeria'
export { default as HeroBanner } from '../components/ecomerce/heroBanner'
export { default as Cart } from '../components/ecomerce/cart'
export { default as Footer } from '../components/ecomerce/footer'
export { default as FooterBanner } from '../components/ecomerce/footerBanner'
export { default as Layout } from '../components/ecomerce/layout'
export { default as NavbarCom } from '../components/ecomerce/navBarCom'
